// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID          int64            `json:"id"`
	ServiceName string           `json:"service_name"`
	Price       int32            `json:"price"`
	UserID      pgtype.UUID      `json:"user_id"`
	SubDate     pgtype.Date      `json:"sub_date"`
	ExpDate     pgtype.Date      `json:"exp_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
