// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	DeleteSubscriptionByID(ctx context.Context, id int64) (int64, error)
	GetSubscriptionByID(ctx context.Context, id int64) (Subscription, error)
	GetSubscriptionsPage(ctx context.Context, arg GetSubscriptionsPageParams) ([]Subscription, error)
	UpdateSubscriptionByID(ctx context.Context, arg UpdateSubscriptionByIDParams) error
}

var _ Querier = (*Queries)(nil)
