// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
}

var _ Querier = (*Queries)(nil)
