// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions
    (service_name, price, user_id, sub_date, exp_date)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING id, service_name, price, user_id, sub_date, exp_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ServiceName string      `json:"service_name"`
	Price       int32       `json:"price"`
	UserID      pgtype.UUID `json:"user_id"`
	SubDate     pgtype.Date `json:"sub_date"`
	ExpDate     pgtype.Date `json:"exp_date"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.SubDate,
		arg.ExpDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.SubDate,
		&i.ExpDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
